version: '3.6'

services:
  
  ethercis-db:    
    build: ./docker_ethercis_db
    ports:
      - "5432:5432"        
    environment:
      - POSTGRES_PASSWORD=postgres

  ethercis-server:
    build: ./docker_ethercis_server
    depends_on:
      - ethercis-db
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=ethercis-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres


