version: '3.6'

services:
  
  ethercis-db:    
    build: ./docker_ethercis_db
    ports:
      - "5432:5432"
    volumes:
      - eth-data-volume:/var/lib/postgresql/data      
    environment:
      - POSTGRES_PASSWORD=postgres

  ethercis-server:
    build: ./docker_ethercis_server
    depends_on:
      - ethercis-db
    ports:
      - "8080:8080"
    volumes:
      - eth-server-logs:/var/opt/ecis/logs
    environment:
      - DB_HOST=ethercis-db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres

volumes:
  eth-data-volume:
  eth-server-logs:

